### ISSUE TITLE
Error parsing Java packages

### ISSUE THREAD

**Issue by jdubois** [thorbenvh8/prettier-java#34] opened 2018-03-27 12:28 UTC
I'm testing with `prettier-java:0.0.2` with a specific patch for handling #31

I have lots of parsing errors, it looks like Java packages are not correctly parsed, here is one example:

```
[error] src/main/java/io/jhipster/demo/aop/logging/LoggingAspect.java: SyntaxError: ';' expected. (1:9)
[error] > 1 | package io.jhipster.demo.aop.logging;
[error]     |         ^
[error]   2 |
[error]   3 | import io.github.jhipster.config.JHipsterConstants;
[error]   4 |
```

In order to give you a full project, which might also have more issues, please have a look at the attached Zip file.: [tmp.zip](https://github.com/thorbenvh8/prettier-java/files/1851956/tmp.zip)

This is a @jhipster application, made from the current `master` branch (which passes our test suite, so it should be quite good).

You need to run `yarn prettier:format` and it should format all `.ts` and `.java` files. It should be pretty comprehensive, so hopefully it will help you catch more issues.

**Comment by thorbenvh8** [comment] 2018-03-28 00:31
Something seems to be very different when releasing it instead of using it from within the project.
```cmd
yarn prettier --write ../jhipster-example/**/*.java 2> errors
```

I get two errors from the parser for code that combines strings, but everything else it runs through like crazy... Will keep this open though for the great example :)

**Comment by thorbenvh8** [comment] 2018-03-28 01:48
Please check version 0.0.4, if you remove all comments from the file it should parse! I tried that. For the status on the comments see: https://github.com/thorbenvh8/prettier-java/issues/32

**Comment by jdubois** [comment] 2018-03-28 08:17
Sorry but I upgraded to `0.0.4` and removed the comments, but still got the same error:
```
[error] src/main/java/io/jhipster/demo/aop/logging/LoggingAspect.java: SyntaxError: ';' expected. (1:9)
[error] > 1 | package io.jhipster.demo.aop.logging;
[error]     |         ^
[error]   2 |
[error]   3 | import io.github.jhipster.config.JHipsterConstants;
[error]   4 |
```

**Comment by thorbenvh8** [comment] 2018-03-28 13:47
Can you checkout this project and run 'yarn test' just to give me an idea if that works.
And after that can you run out of that project 'yarn prettier --write "../tmp/**/*.java"', imagining your tmp project is in the same workspace as prettier-java.

Can't test your project in total because I have not the correct node version, but I did this example project https://github.com/thorbenvh8/jhipster-prettier here, 'yarn prettier LoggingAspect.java' works for me, prints it into the console, add --write to in place replacement.

Can you check if that works, thanks for investing the time solving this with me :)

**Comment by jdubois** [comment] 2018-03-28 13:53
`yarn test` works, and indeed I have different errors:
```
[error] ../../tmp2/src/main/java/io/jhipster/demo/domain/User.java: Error: Sad sad panda, parsing errors detected in line: 222, column: 36!
[error] Expecting: one of these possible Token sequences:
[error]   1. [';']
[error]   2. [';']
[error] but found: '' +
[error]             ", firstName=''
```
So that's definitely an improvement!

**Comment by thorbenvh8** [comment] 2018-03-28 13:56
If you could create an issue with the minimal code that we need to reproduce that error?

And we still have to figure out why its not working when its standalone with comments in the other issue.

Im gonna close this issue! Thanks for helping

**Closed by thorbenvh8** 2018-03-28 13:56 UTC
Labels: bug

**Comment by j-f1** [comment] 2018-03-28 14:53
> Can't test your project in total because I have not the correct node version

If you haven’t already, check out [`nvm`](https://github.com/creationix/nvm) @thorbenvh8.
